-- Migration 1.474: Category tables
-- Promotes categories/decks from free-text strings to first-class DB entities.
-- 4 new tables: todo_categories, habit_categories, vestiaire_categories, flashcard_decks
-- Each item table gets a category_id / deck_id FK column.
-- Old category/deck string columns are kept for transitional compatibility.
--
-- See local-migrations.js (SQLite) and supabase-migrations.js (Postgres) for
-- backend-specific variants. This file is for documentation only.
--
-- Backfills from:
--   - Distinct category/deck values on items
--   - settings JSON keys: todo_category_colors, todo_category_shortnames,
--     habit_category_shortnames, vest_category_shortnames, flash_shortnames
-- Cleans up dead settings keys after backfill.
