-- Migration 1.484: Category integrity hardening
--
-- 1. texts: add missing deck_id FK column (was in supabase FK constraints but
--    not in the texts CREATE TABLE — fresh installs would fail)
-- 2. text_line_progress: drop spurious deck_id column (it inherits deck via
--    text_id → texts.deck_id; no JS reads/writes it)
-- 3. vestiaire.category DEFAULT 'Hauts' → '' (matches protected default row)
-- 4. texts.deck DEFAULT '' (align with other string column defaults)
-- 5. Seed protected rows in base schemas (ON CONFLICT / INSERT OR IGNORE safe)
-- 6. Protection trigger: BEFORE DELETE OR UPDATE on *_categories / flashcard_decks
--    WHERE OLD.is_protected — prevents accidental deletion of default/shared rows
-- 7. FK policy: ON DELETE CASCADE → ON DELETE SET NULL on all category/deck FKs.
--    Items survive category deletion with category_id = NULL; catIdFor*() already
--    falls back to _defaultCatId so they appear in the General bucket.
--
-- See local-migrations.js (SQLite) and supabase-migrations.js (Postgres) for
-- backend-specific variants. This file is for documentation only.
