-- DeLaClaw — Supabase (PostgreSQL) full schema
-- Generated by pg_dump, cleaned of Supabase platform objects.
-- Run this in the Supabase SQL Editor to set up all tables.

-- pgcrypto for digest() — Supabase may install it in extensions or public, try both
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA extensions;

--
-- Name: rls_auto_enable(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


--
-- Name: update_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."update_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = "heap";

--
-- Name: birthdays; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."birthdays" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "birthday" "date" NOT NULL,
    "note" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "avatar_url" "text",
    "owner_id" "uuid"
);


--
-- Name: daily_visits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."daily_visits" (
    "visit_date" "date" NOT NULL,
    "owner_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: flashcard_decks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."flashcard_decks" (
    "id" "text" DEFAULT encode(gen_random_bytes(16), 'hex') NOT NULL,
    "name" "text" NOT NULL,
    "shortname" "text",
    "color" "text",
    "sort_order" integer DEFAULT 0,
    "is_protected" boolean DEFAULT false,
    "owner_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: flashcard_notes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."flashcard_notes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "content" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "proposed_front" "text",
    "proposed_back" "text",
    "proposal_status" "text",
    "proposed_deck" "text",
    "sort_order" integer DEFAULT 0,
    "owner_id" "uuid"
);


--
-- Name: flashcards; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."flashcards" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "deck" "text" DEFAULT ''::text NOT NULL,
    "front" "text" NOT NULL,
    "back" "text" NOT NULL,
    "is_draft" boolean DEFAULT false,
    "stability" real DEFAULT 0,
    "difficulty" real DEFAULT 5,
    "last_review" timestamp with time zone,
    "next_review" timestamp with time zone,
    "review_count" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "owner_id" "uuid",
    "deck_id" "text"
);


--
-- Name: habit_completions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."habit_completions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "habit_id" "uuid",
    "completed_at" timestamp with time zone DEFAULT "now"(),
    "note" "text",
    "owner_id" "uuid"
);


--
-- Name: habits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."habits" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "frequency_rule" "text" NOT NULL,
    "category" "text" DEFAULT ''::text,
    "next_due" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "is_draft" boolean DEFAULT false,
    "owner_id" "uuid",
    "shared_id" "text",
    "shared_group_id" "text",
    "category_id" "text"
);


--
-- Name: habit_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."habit_categories" (
    "id" "text" DEFAULT encode(gen_random_bytes(16), 'hex') NOT NULL,
    "name" "text" NOT NULL,
    "shortname" "text",
    "color" "text",
    "sort_order" integer DEFAULT 0,
    "is_protected" boolean DEFAULT false,
    "owner_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);

CREATE TABLE "public"."list_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "list_id" "uuid",
    "text" "text" NOT NULL,
    "checked" integer DEFAULT 0,
    "note" "text",
    "sort_order" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "owner_id" "uuid",
    "shared_id" "text",
    "shared_group_id" "text"
);


--
-- Name: lists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."lists" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "shortname" "text",
    "color" "text",
    "icon" "text",
    "sort_order" integer DEFAULT 0,
    "archived" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "owner_id" "uuid"
);


--
-- Name: nvidia_usage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."nvidia_usage" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "model" "text" NOT NULL,
    "prompt_tokens" integer DEFAULT 0,
    "completion_tokens" integer DEFAULT 0,
    "total_tokens" integer DEFAULT 0,
    "status" integer NOT NULL,
    "owner_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."projects" (
    "id" "text" NOT NULL,
    "name" "text" NOT NULL,
    "color" "text" DEFAULT '#646cff'::"text" NOT NULL,
    "tech" "text",
    "links" "jsonb" DEFAULT '[]'::"jsonb",
    "sort_order" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "shortname" "text",
    "owner_id" "uuid"
);


--
-- Name: prompts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."prompts" (
    "key" "text" NOT NULL,
    "text" "text" DEFAULT ''::"text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "owner_id" "uuid"
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."settings" (
    "key" "text" NOT NULL,
    "value" "text",
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "owner_id" "uuid"
);


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."tasks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "project" "text" NOT NULL,
    "text" "text" NOT NULL,
    "status" "text" DEFAULT 'todo'::"text" NOT NULL,
    "plan_note" "text",
    "hatch_response" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "sort_order" integer DEFAULT 0,
    CONSTRAINT "plan_max" CHECK (("char_length"("plan_note") <= 5000)),
    CONSTRAINT "response_max" CHECK (("char_length"("hatch_response") <= 5000)),
    CONSTRAINT "tasks_status_check" CHECK (("status" = ANY (ARRAY['todo'::"text", 'in-progress'::"text", 'review'::"text", 'approved'::"text", 'revision'::"text", 'draft'::"text", 'idea'::"text", 'idea-shipped'::"text", 'idea-plan-requested'::"text"]))),
    CONSTRAINT "text_max" CHECK (("char_length"("text") <= 5000)),
    "owner_id" "uuid"
);


--
-- Name: text_line_progress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."text_line_progress" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "text_id" "uuid" NOT NULL,
    "chunk_index" integer NOT NULL,
    "stability" double precision DEFAULT 0 NOT NULL,
    "difficulty" double precision DEFAULT 5 NOT NULL,
    "last_review" timestamp with time zone,
    "next_review" timestamp with time zone,
    "review_count" integer DEFAULT 0 NOT NULL,
    "owner_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


--
-- Name: texts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."texts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "deck" "text" DEFAULT ''::text NOT NULL,
    "title" "text" NOT NULL,
    "author" "text",
    "content" "text" NOT NULL,
    "lines_per_chunk" integer DEFAULT 4 NOT NULL,
    "context_lines" integer DEFAULT 3 NOT NULL,
    "owner_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "deck_id" "text"
);


--
-- Name: todos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."todos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "text" "text" NOT NULL,
    "done" boolean DEFAULT false,
    "priority" "text" DEFAULT 'normal'::"text",
    "due_date" timestamp with time zone,
    "snooze_until" timestamp with time zone,
    "category" "text" DEFAULT ''::"text",
    "sort_order" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "todos_priority_check" CHECK (("priority" = ANY (ARRAY['urgent'::"text", 'high'::"text", 'medium'::"text", 'low'::"text", 'normal'::"text"]))),
    "owner_id" "uuid",
    "shared_id" "text",
    "shared_group_id" "text",
    "category_id" "text"
);


--
-- Name: vestiaire; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."vestiaire" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "category" "text" DEFAULT ''::text NOT NULL,
    "brand" "text",
    "size" "text",
    "color" "text",
    "note" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "purchase_status" "text",
    "sort_order" integer DEFAULT 0,
    "owner_id" "uuid",
    "category_id" "text"
);


--
-- Name: vestiaire_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."vestiaire_categories" (
    "id" "text" DEFAULT encode(gen_random_bytes(16), 'hex') NOT NULL,
    "name" "text" NOT NULL,
    "shortname" "text",
    "color" "text",
    "sort_order" integer DEFAULT 0,
    "is_protected" boolean DEFAULT false,
    "owner_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: todo_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."todo_categories" (
    "id" "text" DEFAULT encode(gen_random_bytes(16), 'hex') NOT NULL,
    "name" "text" NOT NULL,
    "shortname" "text",
    "color" "text",
    "sort_order" integer DEFAULT 0,
    "is_protected" boolean DEFAULT false,
    "owner_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: auth_email_guard; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."auth_email_guard" (
    "email_hash" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: sharing_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."sharing_groups" (
    "id" "text" NOT NULL,
    "name" "text" NOT NULL,
    "backend_type" "text" NOT NULL DEFAULT 'supabase',
    "auth_owner_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: sharing_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."sharing_members" (
    "member_id" "text" NOT NULL,
    "group_id" "text" NOT NULL,
    "token" "text" NOT NULL,
    "token_hash" "text",
    "display_name" "text",
    "invited_label" "text",
    "role" "text" NOT NULL DEFAULT 'member',
    "joined_at" timestamp with time zone,
    "expires_at" timestamp with time zone,
    "revoked_at" timestamp with time zone,
    "auth_user_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: sharing_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."sharing_items" (
    "item_id" "text" NOT NULL,
    "group_id" "text" NOT NULL,
    "item_type" "text" NOT NULL,
    "parent_item_id" "text",
    "payload" "jsonb" NOT NULL,
    "created_by" "text",
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "created_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: joined_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."joined_groups" (
    "group_id" "text" NOT NULL,
    "member_id" "text" NOT NULL,
    "token_ciphertext" "text",
    "token_iv" "text",
    "display_name" "text",
    "group_name" "text",
    "remote_backend_type" "text" NOT NULL,
    "remote_url" "text",
    "remote_anon_key_ciphertext" "text",
    "remote_anon_key_iv" "text",
    "owner_id" "uuid",
    "joined_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: verify_join_token; Type: FUNCTION; Schema: public; Owner: postgres
-- 1.301: uses token_hash + expiry + revocation
-- 1.399: creator attribution via auth_user_id
-- 1.402: explicit casts + pgcrypto
--

CREATE OR REPLACE FUNCTION "public"."verify_join_token"("p_token" "text")
RETURNS TABLE("group_id" "text", "group_name" "text", "member_id" "text",
              "display_name" "text", "invited_label" "text", "backend_type" "text", "creator_name" "text")
LANGUAGE "sql" SECURITY DEFINER SET search_path = public, extensions AS $$
  SELECT sg.id, sg.name, sm.member_id, sm.display_name, sm.invited_label, sg.backend_type,
         (SELECT cm.display_name FROM sharing_members cm
          WHERE cm.group_id = sg.id AND cm.role = 'creator' LIMIT 1)
  FROM sharing_members sm
  JOIN sharing_groups sg ON sg.id = sm.group_id
  WHERE sm.token_hash = encode(digest(p_token::text, 'sha256'::text), 'hex'::text)
    AND sm.revoked_at IS NULL
    AND (sm.expires_at IS NULL OR sm.expires_at > now())
    AND sm.joined_at IS NULL;
$$;


--
-- Name: confirm_join; Type: FUNCTION; Schema: public; Owner: postgres
-- 1.399: set auth_user_id on confirm for stable attribution
-- 1.402: casts
--

CREATE OR REPLACE FUNCTION "public"."confirm_join"("p_token" "text", "p_display_name" "text")
RETURNS "void"
LANGUAGE "sql" SECURITY DEFINER SET search_path = public, extensions AS $$
  UPDATE sharing_members
  SET joined_at = now(),
      display_name = COALESCE(NULLIF(p_display_name, ''::text), display_name, invited_label),
      auth_user_id = COALESCE(auth_user_id, auth.uid())
  WHERE token_hash = encode(digest(p_token::text, 'sha256'::text), 'hex'::text)
    AND joined_at IS NULL
    AND revoked_at IS NULL
    AND (expires_at IS NULL OR expires_at > now());
$$;


--
-- Name: get_shared_items; Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."get_shared_items"("p_token" "text", "p_group_id" "text",
                                                        "p_item_type" "text" DEFAULT NULL::text)
RETURNS SETOF "public"."sharing_items"
LANGUAGE "sql" SECURITY DEFINER SET search_path = public, extensions AS $$
  SELECT si.* FROM sharing_items si
  WHERE si.group_id = p_group_id
  AND (p_item_type IS NULL OR si.item_type = p_item_type)
  AND EXISTS (
    SELECT 1 FROM sharing_members sm
    WHERE sm.group_id = p_group_id
    AND sm.token_hash = encode(digest(p_token::text, 'sha256'::text), 'hex'::text)
    AND sm.joined_at IS NOT NULL
    AND sm.revoked_at IS NULL
  );
$$;


--
-- Name: add_shared_item; Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."add_shared_item"(
  "p_token" "text", "p_item_id" "text", "p_group_id" "text", "p_item_type" "text",
  "p_payload" "jsonb", "p_member_id" "text", "p_parent_item_id" "text" DEFAULT NULL::text
)
RETURNS SETOF "public"."sharing_items"
LANGUAGE "sql" SECURITY DEFINER SET search_path = public, extensions AS $$
  INSERT INTO sharing_items
    (item_id, group_id, item_type, parent_item_id, payload, created_by)
  SELECT p_item_id, p_group_id, p_item_type,
         p_parent_item_id, p_payload, p_member_id
  WHERE EXISTS (
    SELECT 1 FROM sharing_members sm
    WHERE sm.group_id = p_group_id
    AND sm.token_hash = encode(digest(p_token::text, 'sha256'::text), 'hex'::text)
    AND sm.member_id = p_member_id
    AND sm.joined_at IS NOT NULL
    AND sm.revoked_at IS NULL
  )
  RETURNING *;
$$;


--
-- Name: update_shared_item; Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."update_shared_item"("p_token" "text", "p_item_id" "text",
                                                          "p_payload" "jsonb")
RETURNS SETOF "public"."sharing_items"
LANGUAGE "sql" SECURITY DEFINER SET search_path = public, extensions AS $$
  UPDATE sharing_items si
  SET payload = p_payload, updated_at = now()
  WHERE si.item_id = p_item_id
  AND EXISTS (
    SELECT 1 FROM sharing_members sm
    WHERE sm.group_id = si.group_id
    AND sm.token_hash = encode(digest(p_token::text, 'sha256'::text), 'hex'::text)
    AND sm.joined_at IS NOT NULL
    AND sm.revoked_at IS NULL
  )
  RETURNING *;
$$;


--
-- Name: delete_shared_item; Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."delete_shared_item"("p_token" "text", "p_item_id" "text")
RETURNS "void"
LANGUAGE "plpgsql" SECURITY DEFINER SET search_path = public, extensions AS $$
BEGIN
  DELETE FROM sharing_items si
  WHERE si.item_id = p_item_id
  AND EXISTS (
    SELECT 1 FROM sharing_members sm
    WHERE sm.group_id = si.group_id
    AND sm.token_hash = encode(digest(p_token::text, 'sha256'::text), 'hex'::text)
    AND sm.joined_at IS NOT NULL
    AND sm.revoked_at IS NULL
  );
END;
$$;


--
-- Name: get_group_members; Type: FUNCTION; Schema: public; Owner: postgres
-- 1.399: include auth_user_id for stable attribution
-- 1.402: casts
-- 1.452: filter revoked members from outer query
--

CREATE OR REPLACE FUNCTION "public"."get_group_members"("p_token" "text", "p_group_id" "text")
RETURNS TABLE("member_id" "text", "display_name" "text", "invited_label" "text", "role" "text",
              "joined_at" timestamp with time zone, "auth_user_id" "uuid")
LANGUAGE "sql" SECURITY DEFINER SET search_path = public, extensions AS $$
  SELECT sm.member_id, sm.display_name, sm.invited_label, sm.role, sm.joined_at, sm.auth_user_id
  FROM sharing_members sm
  WHERE sm.group_id = p_group_id
  AND sm.revoked_at IS NULL
  AND EXISTS (
    SELECT 1 FROM sharing_members sm2
    WHERE sm2.group_id = p_group_id
    AND sm2.token_hash = encode(digest(p_token::text, 'sha256'::text), 'hex'::text)
    AND sm2.joined_at IS NOT NULL
    AND sm2.revoked_at IS NULL
  );
$$;


--
-- Name: leave_group; Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."leave_group"("p_token" "text")
RETURNS "void"
LANGUAGE "plpgsql" SECURITY DEFINER SET search_path = public, extensions AS $$
BEGIN
  DELETE FROM sharing_members
  WHERE token_hash = encode(digest(p_token::text, 'sha256'::text), 'hex'::text)
  AND role != 'creator'
  AND joined_at IS NOT NULL
  AND revoked_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."revoke_member"("p_group_id" "text", "p_member_id" "text")
RETURNS "void"
LANGUAGE "sql" SECURITY DEFINER SET search_path = public, extensions AS $$
  UPDATE sharing_members
  SET revoked_at = now()
  WHERE group_id = p_group_id
    AND member_id = p_member_id
    AND role != 'creator';
$$;

CREATE OR REPLACE FUNCTION "public"."update_member_display_name"("p_token" "text", "p_display_name" "text")
RETURNS "void"
LANGUAGE "plpgsql" SECURITY DEFINER SET search_path = public, extensions AS $$
BEGIN
  UPDATE sharing_members
  SET display_name = p_display_name
  WHERE token_hash = encode(digest(p_token, 'sha256'), 'hex')
    AND joined_at IS NOT NULL
    AND revoked_at IS NULL;
END;
$$;


--
-- Name: birthdays birthdays_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."birthdays"
    ADD CONSTRAINT "birthdays_pkey" PRIMARY KEY ("id");


--
-- Name: habit_completions chore_completions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."habit_completions"
    ADD CONSTRAINT "chore_completions_pkey" PRIMARY KEY ("id");


--
-- Name: habits chores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."habits"
    ADD CONSTRAINT "chores_pkey" PRIMARY KEY ("id");


--
-- Name: daily_visits daily_visits_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."daily_visits"
    ADD CONSTRAINT "daily_visits_pkey" PRIMARY KEY ("visit_date", "owner_id");


--
-- Name: flashcard_notes flashcard_notes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."flashcard_notes"
    ADD CONSTRAINT "flashcard_notes_pkey" PRIMARY KEY ("id");


--
-- Name: flashcards flashcards_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."flashcards"
    ADD CONSTRAINT "flashcards_pkey" PRIMARY KEY ("id");


--
-- Name: list_items list_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."list_items"
    ADD CONSTRAINT "list_items_pkey" PRIMARY KEY ("id");


--
-- Name: lists lists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."lists"
    ADD CONSTRAINT "lists_pkey" PRIMARY KEY ("id");


--
-- Name: nvidia_usage nvidia_usage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."nvidia_usage"
    ADD CONSTRAINT "nvidia_usage_pkey" PRIMARY KEY ("id");


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."projects"
    ADD CONSTRAINT "projects_pkey" PRIMARY KEY ("id");


--
-- Name: prompts prompts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."prompts"
    ADD CONSTRAINT "prompts_pkey" PRIMARY KEY ("key");


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."settings"
    ADD CONSTRAINT "settings_pkey" PRIMARY KEY ("key");


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_pkey" PRIMARY KEY ("id");


--
-- Name: text_line_progress text_line_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."text_line_progress"
    ADD CONSTRAINT "text_line_progress_pkey" PRIMARY KEY ("id");


--
-- Name: texts texts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."texts"
    ADD CONSTRAINT "texts_pkey" PRIMARY KEY ("id");


--
-- Name: todos todos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."todos"
    ADD CONSTRAINT "todos_pkey" PRIMARY KEY ("id");


--
-- Name: vestiaire vestiaire_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."vestiaire"
    ADD CONSTRAINT "vestiaire_pkey" PRIMARY KEY ("id");


--
-- Name: todo_categories todo_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."todo_categories"
    ADD CONSTRAINT "todo_categories_pkey" PRIMARY KEY ("id");


--
-- Name: habit_categories habit_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."habit_categories"
    ADD CONSTRAINT "habit_categories_pkey" PRIMARY KEY ("id");


--
-- Name: vestiaire_categories vestiaire_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."vestiaire_categories"
    ADD CONSTRAINT "vestiaire_categories_pkey" PRIMARY KEY ("id");


--
-- Name: flashcard_decks flashcard_decks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."flashcard_decks"
    ADD CONSTRAINT "flashcard_decks_pkey" PRIMARY KEY ("id");


--
-- Name: auth_email_guard auth_email_guard_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."auth_email_guard"
    ADD CONSTRAINT "auth_email_guard_pkey" PRIMARY KEY ("email_hash");


--
-- Name: sharing_groups sharing_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."sharing_groups"
    ADD CONSTRAINT "sharing_groups_pkey" PRIMARY KEY ("id");


--
-- Name: sharing_members sharing_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."sharing_members"
    ADD CONSTRAINT "sharing_members_pkey" PRIMARY KEY ("member_id");


--
-- Name: sharing_members sharing_members_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."sharing_members"
    ADD CONSTRAINT "sharing_members_token_key" UNIQUE ("token");


--
-- Name: sharing_items sharing_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."sharing_items"
    ADD CONSTRAINT "sharing_items_pkey" PRIMARY KEY ("item_id");


--
-- Name: joined_groups joined_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."joined_groups"
    ADD CONSTRAINT "joined_groups_pkey" PRIMARY KEY ("group_id");


--
-- Name: prompts prompts_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER "prompts_updated_at" BEFORE UPDATE ON "public"."prompts" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();


--
-- Name: todos set_todos_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER "set_todos_updated_at" BEFORE UPDATE ON "public"."todos" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();


--
-- Name: habits set_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER "set_updated_at" BEFORE UPDATE ON "public"."habits" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();


--
-- Name: tasks tasks_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER "tasks_updated_at" BEFORE UPDATE ON "public"."tasks" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();


--
-- Name: habit_completions chore_completions_chore_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."habit_completions"
    ADD CONSTRAINT "chore_completions_chore_id_fkey" FOREIGN KEY ("habit_id") REFERENCES "public"."habits"("id") ON DELETE CASCADE;


--
-- Name: list_items list_items_list_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."list_items"
    ADD CONSTRAINT "list_items_list_id_fkey" FOREIGN KEY ("list_id") REFERENCES "public"."lists"("id") ON DELETE CASCADE;


--
-- Name: text_line_progress text_line_progress_text_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."text_line_progress"
    ADD CONSTRAINT "text_line_progress_text_id_fkey" FOREIGN KEY ("text_id") REFERENCES "public"."texts"("id") ON DELETE CASCADE;


--
-- Name: sharing_members sharing_members_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."sharing_members"
    ADD CONSTRAINT "sharing_members_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."sharing_groups"("id") ON DELETE CASCADE;


--
-- Name: sharing_items sharing_items_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."sharing_items"
    ADD CONSTRAINT "sharing_items_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."sharing_groups"("id") ON DELETE CASCADE;


--
-- Name: sharing_items sharing_items_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."sharing_items"
    ADD CONSTRAINT "sharing_items_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."sharing_members"("member_id");


--
-- Name: todos todos_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."todos"
    ADD CONSTRAINT "todos_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."todo_categories"("id") ON DELETE CASCADE;


--
-- Name: habits habits_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."habits"
    ADD CONSTRAINT "habits_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."habit_categories"("id") ON DELETE CASCADE;


--
-- Name: vestiaire vestiaire_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."vestiaire"
    ADD CONSTRAINT "vestiaire_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."vestiaire_categories"("id") ON DELETE CASCADE;


--
-- Name: flashcards flashcards_deck_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."flashcards"
    ADD CONSTRAINT "flashcards_deck_id_fkey" FOREIGN KEY ("deck_id") REFERENCES "public"."flashcard_decks"("id") ON DELETE CASCADE;


--
-- Name: texts texts_deck_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."texts"
    ADD CONSTRAINT "texts_deck_id_fkey" FOREIGN KEY ("deck_id") REFERENCES "public"."flashcard_decks"("id") ON DELETE CASCADE;


--
-- ===== ROW LEVEL SECURITY: ENABLE =====
--

ALTER TABLE "public"."birthdays" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."daily_visits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."flashcard_notes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."flashcards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."habit_completions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."habits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."list_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."lists" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."nvidia_usage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."projects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."prompts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tasks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."text_line_progress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."texts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."todos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."vestiaire" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."sharing_groups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."sharing_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."sharing_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."joined_groups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."todo_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."habit_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."vestiaire_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."flashcard_decks" ENABLE ROW LEVEL SECURITY;


--
-- ===== ROW LEVEL SECURITY: POLICIES =====
--
-- Personal tables use "owner only": owner_id = auth.uid().
-- Supabase backend now requires mandatory auth — anon sees 0 rows.
-- Use claim_ownership() SECURITY DEFINER to claim legacy NULL rows.
-- Auto-set owner_id via trg_set_owner_id BEFORE INSERT trigger.
--

-- ── Helper functions ──
CREATE OR REPLACE FUNCTION set_owner_id()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.owner_id IS NULL THEN
    NEW.owner_id := auth.uid();
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION claim_ownership()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE uid UUID := auth.uid();
BEGIN
  IF uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  -- Delete orphan daily_visits that would conflict on PK
  BEGIN DELETE FROM daily_visits WHERE owner_id IS NULL AND visit_date IN (SELECT visit_date FROM daily_visits WHERE owner_id = uid); EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE projects SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE tasks SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE todos SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE habits SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE habit_completions SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE flashcards SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE flashcard_notes SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE texts SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE text_line_progress SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE birthdays SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE vestiaire SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE lists SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE list_items SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE settings SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE prompts SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE nvidia_usage SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE daily_visits SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table OR unique_violation THEN NULL; END;
  BEGIN UPDATE joined_groups SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE agent_grants SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE todo_categories SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE habit_categories SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE vestiaire_categories SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
  BEGIN UPDATE flashcard_decks SET owner_id = uid WHERE owner_id IS NULL; EXCEPTION WHEN undefined_table THEN NULL; END;
END;
$$;

-- ===== 1.410 Agent grants — multi-token API =====
CREATE TABLE IF NOT EXISTS "public"."agent_grants" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL,
  display_name TEXT NOT NULL,
  token_hash TEXT UNIQUE NOT NULL,
  scope TEXT NOT NULL DEFAULT 'full',
  last_used_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE "public"."agent_grants" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "owner only" ON "public"."agent_grants";
CREATE POLICY "owner only" ON "public"."agent_grants" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE INDEX IF NOT EXISTS idx_agent_grants_owner_id ON "public"."agent_grants"(owner_id);
CREATE INDEX IF NOT EXISTS idx_agent_grants_token_hash ON "public"."agent_grants"(token_hash);
DROP TRIGGER IF EXISTS trg_set_owner_id ON "public"."agent_grants";
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."agent_grants" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE OR REPLACE FUNCTION has_agent_access(target_owner UUID)
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, extensions AS $$
DECLARE hdr TEXT; tok TEXT; h TEXT; matched_id UUID;
BEGIN
  IF target_owner IS NULL THEN RETURN FALSE; END IF;
  BEGIN hdr := current_setting('request.headers', true); EXCEPTION WHEN OTHERS THEN RETURN FALSE; END;
  IF hdr IS NULL OR hdr = '' THEN RETURN FALSE; END IF;
  BEGIN tok := (hdr::jsonb ->> 'x-agent-token'); IF tok IS NULL OR tok = '' THEN tok := (hdr::jsonb ->> 'X-Agent-Token'); END IF; IF tok IS NULL OR tok = '' THEN tok := (hdr::jsonb ->> 'x-api-token'); END IF; EXCEPTION WHEN OTHERS THEN RETURN FALSE; END;
  IF tok IS NULL OR tok = '' THEN RETURN FALSE; END IF;
  h := encode(digest(tok::text, 'sha256'::text), 'hex'::text);
  SELECT id INTO matched_id FROM agent_grants WHERE owner_id = target_owner AND token_hash = h AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now()) LIMIT 1;
  IF matched_id IS NULL THEN RETURN FALSE; END IF;
  BEGIN UPDATE agent_grants SET last_used_at = now() WHERE id = matched_id AND (last_used_at IS NULL OR last_used_at < now() - INTERVAL '5 minutes'); EXCEPTION WHEN OTHERS THEN NULL; END;
  RETURN TRUE;
END; $$;

CREATE OR REPLACE FUNCTION create_agent_grant(p_display_name TEXT, p_scope TEXT DEFAULT 'full')
RETURNS TABLE(id UUID, token TEXT, display_name TEXT, scope TEXT, created_at TIMESTAMPTZ)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, extensions AS $$
DECLARE uid UUID := auth.uid(); raw TEXT; hash TEXT; new_id UUID; new_created TIMESTAMPTZ;
BEGIN
  IF uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF p_display_name IS NULL OR btrim(p_display_name) = '' THEN RAISE EXCEPTION 'display_name required'; END IF;
  raw := encode(gen_random_bytes(32), 'hex');
  hash := encode(digest(raw::text, 'sha256'::text), 'hex'::text);
  INSERT INTO agent_grants (owner_id, display_name, token_hash, scope) VALUES (uid, btrim(p_display_name), hash, COALESCE(p_scope,'full')) RETURNING agent_grants.id, agent_grants.created_at INTO new_id, new_created;
  RETURN QUERY SELECT new_id, raw, btrim(p_display_name), COALESCE(p_scope,'full'), new_created;
END; $$;

CREATE OR REPLACE FUNCTION revoke_agent_grant(p_id UUID) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, extensions AS $$
DECLARE uid UUID := auth.uid(); BEGIN IF uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF; UPDATE agent_grants SET revoked_at = now() WHERE id = p_id AND owner_id = uid AND revoked_at IS NULL; END; $$;

CREATE OR REPLACE FUNCTION touch_agent_grant() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, extensions AS $$
DECLARE hdr TEXT; tok TEXT; h TEXT; BEGIN
  BEGIN hdr := current_setting('request.headers', true); EXCEPTION WHEN OTHERS THEN RETURN; END;
  IF hdr IS NULL THEN RETURN; END IF;
  BEGIN tok := (hdr::jsonb ->> 'x-agent-token'); IF tok IS NULL OR tok = '' THEN tok := (hdr::jsonb ->> 'X-Agent-Token'); END IF; EXCEPTION WHEN OTHERS THEN RETURN; END;
  IF tok IS NULL OR tok = '' THEN RETURN; END IF;
  h := encode(digest(tok::text, 'sha256'::text), 'hex'::text);
  UPDATE agent_grants SET last_used_at = now() WHERE token_hash = h;
END; $$;
-- ── Personal tables (owner or agent) ──────────────────────

CREATE POLICY "owner or agent" ON "public"."birthdays" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."birthdays" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."flashcard_notes" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."flashcard_notes" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."habit_completions" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."habit_completions" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."habits" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."habits" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."list_items" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."list_items" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."lists" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."lists" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."projects" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."projects" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."prompts" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."prompts" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."settings" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."settings" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."tasks" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."tasks" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."todos" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."todos" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."vestiaire" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."vestiaire" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."daily_visits" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."daily_visits" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."flashcards" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."flashcards" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."nvidia_usage" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."nvidia_usage" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."text_line_progress" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."text_line_progress" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."texts" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."texts" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

-- ── Sharing tables ────────────────────────────────────────────

CREATE POLICY "owner or agent" ON "public"."sharing_groups" FOR ALL USING (auth_owner_id = auth.uid() OR has_agent_access(auth_owner_id)) WITH CHECK (auth_owner_id = auth.uid() OR has_agent_access(auth_owner_id));

CREATE POLICY "owner or agent" ON "public"."sharing_members" FOR ALL USING (group_id IN (SELECT id FROM sharing_groups WHERE auth_owner_id = auth.uid() OR has_agent_access(auth_owner_id))) WITH CHECK (group_id IN (SELECT id FROM sharing_groups WHERE auth_owner_id = auth.uid() OR has_agent_access(auth_owner_id)));

CREATE POLICY "owner or agent" ON "public"."sharing_items" FOR ALL USING (group_id IN (SELECT id FROM sharing_groups WHERE auth_owner_id = auth.uid() OR has_agent_access(auth_owner_id))) WITH CHECK (group_id IN (SELECT id FROM sharing_groups WHERE auth_owner_id = auth.uid() OR has_agent_access(auth_owner_id)));

CREATE POLICY "owner or agent" ON "public"."joined_groups" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."joined_groups" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

-- ── Category tables ──
CREATE POLICY "owner or agent" ON "public"."todo_categories" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."todo_categories" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."habit_categories" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."habit_categories" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."vestiaire_categories" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."vestiaire_categories" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner or agent" ON "public"."flashcard_decks" FOR ALL USING (owner_id = auth.uid() OR has_agent_access(owner_id)) WITH CHECK (owner_id = auth.uid() OR has_agent_access(owner_id));
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."flashcard_decks" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

-- ── Auth email guard (1.453) — no RLS, anon must SELECT pre-auth ──
GRANT SELECT ON "public"."auth_email_guard" TO anon;
GRANT SELECT, INSERT ON "public"."auth_email_guard" TO authenticated;


-- ===== SEED DATA =====

-- ===== INDEXES (perf — avoid seq scans on RLS owner_id lookups + shared pointers) =====
CREATE INDEX IF NOT EXISTS idx_projects_owner_id ON "public"."projects" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_tasks_owner_id ON "public"."tasks" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_todos_owner_id ON "public"."todos" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_habits_owner_id ON "public"."habits" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_habit_completions_owner_id ON "public"."habit_completions" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_flashcards_owner_id ON "public"."flashcards" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_flashcard_notes_owner_id ON "public"."flashcard_notes" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_texts_owner_id ON "public"."texts" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_text_line_progress_owner_id ON "public"."text_line_progress" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_birthdays_owner_id ON "public"."birthdays" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_vestiaire_owner_id ON "public"."vestiaire" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_lists_owner_id ON "public"."lists" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_list_items_owner_id ON "public"."list_items" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_prompts_owner_id ON "public"."prompts" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_settings_owner_id ON "public"."settings" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_nvidia_usage_owner_id ON "public"."nvidia_usage" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_daily_visits_owner_id ON "public"."daily_visits" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_joined_groups_owner_id ON "public"."joined_groups" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_todos_shared_id ON "public"."todos" ("shared_id");
CREATE INDEX IF NOT EXISTS idx_todos_shared_group_id ON "public"."todos" ("shared_group_id");
CREATE INDEX IF NOT EXISTS idx_habits_shared_id ON "public"."habits" ("shared_id");
CREATE INDEX IF NOT EXISTS idx_habits_shared_group_id ON "public"."habits" ("shared_group_id");
CREATE INDEX IF NOT EXISTS idx_list_items_shared_id ON "public"."list_items" ("shared_id");
CREATE INDEX IF NOT EXISTS idx_list_items_shared_group_id ON "public"."list_items" ("shared_group_id");
CREATE INDEX IF NOT EXISTS idx_sharing_groups_auth_owner_id ON "public"."sharing_groups" ("auth_owner_id");
CREATE INDEX IF NOT EXISTS idx_sharing_members_group_id ON "public"."sharing_members" ("group_id");
CREATE INDEX IF NOT EXISTS idx_sharing_members_token_hash ON "public"."sharing_members" ("token_hash");
CREATE INDEX IF NOT EXISTS idx_sharing_members_auth_user_id ON "public"."sharing_members" ("auth_user_id");
CREATE INDEX IF NOT EXISTS idx_sharing_members_group_auth ON "public"."sharing_members" ("group_id", "auth_user_id");
CREATE INDEX IF NOT EXISTS idx_sharing_items_group_id ON "public"."sharing_items" ("group_id");
CREATE INDEX IF NOT EXISTS idx_todo_categories_owner_id ON "public"."todo_categories" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_habit_categories_owner_id ON "public"."habit_categories" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_vestiaire_categories_owner_id ON "public"."vestiaire_categories" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_flashcard_decks_owner_id ON "public"."flashcard_decks" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_todos_category_id ON "public"."todos" ("category_id");
CREATE INDEX IF NOT EXISTS idx_habits_category_id ON "public"."habits" ("category_id");
CREATE INDEX IF NOT EXISTS idx_vestiaire_category_id ON "public"."vestiaire" ("category_id");
CREATE INDEX IF NOT EXISTS idx_flashcards_deck_id ON "public"."flashcards" ("deck_id");
CREATE INDEX IF NOT EXISTS idx_texts_deck_id ON "public"."texts" ("deck_id");


INSERT INTO "public"."settings" ("key", "value") VALUES ('db_created_at', to_jsonb(now()::text))
ON CONFLICT ("key") DO NOTHING;

-- ===== REALTIME =====
-- Enable Supabase Realtime for cross-device live sync
ALTER PUBLICATION supabase_realtime ADD TABLE
  tasks, projects, todos, habits, habit_completions,
  birthdays, vestiaire, flashcards, flashcard_notes,
  prompts, settings, lists, list_items, daily_visits,
  sharing_groups, sharing_members, sharing_items,
  todo_categories, habit_categories, vestiaire_categories, flashcard_decks;


INSERT INTO "public"."settings" ("key", "value") VALUES ('schema_version', '1.651') ON CONFLICT ("key") DO UPDATE SET "value" = '1.651', "updated_at" = now();

-- ── Seed protected category rows (ON CONFLICT safe for idempotent re-runs) ──
-- owner_id is NULL here; trg_set_owner_id fills it on first auth'd INSERT.
-- Fresh installs run claim_ownership() which backfills owner_id.
INSERT INTO "public"."todo_categories" ("name", "is_protected", "sort_order") VALUES ('', TRUE, 0);
INSERT INTO "public"."todo_categories" ("name", "is_protected", "sort_order") VALUES ('__shared__', TRUE, 9999);
INSERT INTO "public"."habit_categories" ("name", "is_protected", "sort_order") VALUES ('', TRUE, 0);
INSERT INTO "public"."habit_categories" ("name", "is_protected", "sort_order") VALUES ('__shared__', TRUE, 9999);
INSERT INTO "public"."vestiaire_categories" ("name", "is_protected", "sort_order") VALUES ('', TRUE, 0);
INSERT INTO "public"."vestiaire_categories" ("name", "is_protected", "sort_order") VALUES ('__shared__', TRUE, 9999);
INSERT INTO "public"."flashcard_decks" ("name", "is_protected", "sort_order") VALUES ('', TRUE, 0);
INSERT INTO "public"."flashcard_decks" ("name", "is_protected", "sort_order") VALUES ('__shared__', TRUE, 9999);

-- ── Protection trigger: prevent DELETE or UPDATE of is_protected rows ──
CREATE OR REPLACE FUNCTION "public"."protect_category_row"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.is_protected THEN
      RAISE EXCEPTION 'Cannot delete protected row %', OLD.id;
    END IF;
    RETURN OLD;
  ELSIF TG_OP = 'UPDATE' THEN
    -- allow claim: NULL->uid, name/flag unchanged
    IF OLD.is_protected AND OLD.owner_id IS NULL AND NEW.owner_id IS NOT NULL THEN
      IF OLD.name IS DISTINCT FROM NEW.name OR OLD.is_protected IS DISTINCT FROM NEW.is_protected THEN
        RAISE EXCEPTION 'Cannot change name/flag of protected %', OLD.id;
      END IF;
      RETURN NEW;
    END IF;
    -- allow color/shortname/sort_order for protected, block name/id/protected changes
    IF OLD.is_protected AND (OLD.name IS DISTINCT FROM NEW.name OR OLD.id IS DISTINCT FROM NEW.id OR OLD.is_protected IS DISTINCT FROM NEW.is_protected) THEN
      RAISE EXCEPTION 'Cannot modify protected row % (only color/shortname/sort_order)', OLD.id;
    END IF;
    RETURN NEW;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_protect_todo_categories BEFORE DELETE OR UPDATE ON "public"."todo_categories" FOR EACH ROW WHEN (OLD.is_protected = TRUE) EXECUTE FUNCTION "public"."protect_category_row"();
CREATE TRIGGER trg_protect_habit_categories BEFORE DELETE OR UPDATE ON "public"."habit_categories" FOR EACH ROW WHEN (OLD.is_protected = TRUE) EXECUTE FUNCTION "public"."protect_category_row"();
CREATE TRIGGER trg_protect_vestiaire_categories BEFORE DELETE OR UPDATE ON "public"."vestiaire_categories" FOR EACH ROW WHEN (OLD.is_protected = TRUE) EXECUTE FUNCTION "public"."protect_category_row"();
CREATE TRIGGER trg_protect_flashcard_decks BEFORE DELETE OR UPDATE ON "public"."flashcard_decks" FOR EACH ROW WHEN (OLD.is_protected = TRUE) EXECUTE FUNCTION "public"."protect_category_row"();
