-- DeLaClaw — Supabase (PostgreSQL) full schema
-- Generated by pg_dump, cleaned of Supabase platform objects.
-- Run this in the Supabase SQL Editor to set up all tables.

--
-- Name: rls_auto_enable(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


--
-- Name: update_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."update_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = "heap";

--
-- Name: birthdays; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."birthdays" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "birthday" "date" NOT NULL,
    "note" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "avatar_url" "text",
    "owner_id" "uuid"
);


--
-- Name: daily_visits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."daily_visits" (
    "visit_date" "date" NOT NULL,
    "owner_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: flashcard_notes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."flashcard_notes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "content" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "proposed_front" "text",
    "proposed_back" "text",
    "proposal_status" "text",
    "proposed_deck" "text",
    "owner_id" "uuid"
);


--
-- Name: flashcards; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."flashcards" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "deck" "text" DEFAULT 'Général'::"text" NOT NULL,
    "front" "text" NOT NULL,
    "back" "text" NOT NULL,
    "is_draft" boolean DEFAULT false,
    "stability" real DEFAULT 0,
    "difficulty" real DEFAULT 5,
    "last_review" timestamp with time zone,
    "next_review" timestamp with time zone,
    "review_count" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "owner_id" "uuid"
);


--
-- Name: habit_completions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."habit_completions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "habit_id" "uuid",
    "completed_at" timestamp with time zone DEFAULT "now"(),
    "note" "text",
    "owner_id" "uuid"
);


--
-- Name: habits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."habits" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "frequency_rule" "text" NOT NULL,
    "category" "text" DEFAULT 'General'::"text",
    "next_due" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "is_draft" boolean DEFAULT false,
    "owner_id" "uuid"
);


--
-- Name: list_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."list_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "list_id" "uuid",
    "text" "text" NOT NULL,
    "checked" integer DEFAULT 0,
    "note" "text",
    "sort_order" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "owner_id" "uuid"
);


--
-- Name: lists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."lists" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "color" "text",
    "icon" "text",
    "sort_order" integer DEFAULT 0,
    "archived" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "owner_id" "uuid"
);


--
-- Name: nvidia_usage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."nvidia_usage" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "model" "text" NOT NULL,
    "prompt_tokens" integer DEFAULT 0,
    "completion_tokens" integer DEFAULT 0,
    "total_tokens" integer DEFAULT 0,
    "status" integer NOT NULL,
    "owner_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."projects" (
    "id" "text" NOT NULL,
    "name" "text" NOT NULL,
    "color" "text" DEFAULT '#646cff'::"text" NOT NULL,
    "tech" "text",
    "links" "jsonb" DEFAULT '[]'::"jsonb",
    "sort_order" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "shortname" "text",
    "owner_id" "uuid"
);


--
-- Name: prompts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."prompts" (
    "key" "text" NOT NULL,
    "text" "text" DEFAULT ''::"text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "owner_id" "uuid"
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."settings" (
    "key" "text" NOT NULL,
    "value" "text",
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "owner_id" "uuid"
);


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."tasks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "project" "text" NOT NULL,
    "text" "text" NOT NULL,
    "status" "text" DEFAULT 'todo'::"text" NOT NULL,
    "plan_note" "text",
    "hatch_response" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "sort_order" integer DEFAULT 0,
    CONSTRAINT "plan_max" CHECK (("char_length"("plan_note") <= 5000)),
    CONSTRAINT "response_max" CHECK (("char_length"("hatch_response") <= 5000)),
    CONSTRAINT "tasks_status_check" CHECK (("status" = ANY (ARRAY['todo'::"text", 'in-progress'::"text", 'review'::"text", 'approved'::"text", 'revision'::"text", 'draft'::"text", 'idea'::"text", 'idea-shipped'::"text", 'idea-plan-requested'::"text"]))),
    CONSTRAINT "text_max" CHECK (("char_length"("text") <= 5000)),
    "owner_id" "uuid"
);


--
-- Name: text_line_progress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."text_line_progress" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "text_id" "uuid" NOT NULL,
    "chunk_index" integer NOT NULL,
    "stability" double precision DEFAULT 0 NOT NULL,
    "difficulty" double precision DEFAULT 5 NOT NULL,
    "last_review" timestamp with time zone,
    "next_review" timestamp with time zone,
    "review_count" integer DEFAULT 0 NOT NULL,
    "owner_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


--
-- Name: texts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."texts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "deck" "text" NOT NULL,
    "title" "text" NOT NULL,
    "author" "text",
    "content" "text" NOT NULL,
    "lines_per_chunk" integer DEFAULT 4 NOT NULL,
    "context_lines" integer DEFAULT 3 NOT NULL,
    "owner_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


--
-- Name: todos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."todos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "text" "text" NOT NULL,
    "done" boolean DEFAULT false,
    "priority" "text" DEFAULT 'normal'::"text",
    "due_date" timestamp with time zone,
    "snooze_until" timestamp with time zone,
    "category" "text" DEFAULT ''::"text",
    "sort_order" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "todos_priority_check" CHECK (("priority" = ANY (ARRAY['urgent'::"text", 'high'::"text", 'medium'::"text", 'low'::"text", 'normal'::"text"]))),
    "owner_id" "uuid"
);


--
-- Name: vestiaire; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."vestiaire" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "category" "text" DEFAULT 'Hauts'::"text" NOT NULL,
    "brand" "text",
    "size" "text",
    "color" "text",
    "note" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "purchase_status" "text",
    "sort_order" integer DEFAULT 0,
    "owner_id" "uuid"
);


--
-- Name: sharing_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."sharing_groups" (
    "id" "text" NOT NULL,
    "name" "text" NOT NULL,
    "backend_type" "text" NOT NULL DEFAULT 'supabase',
    "auth_owner_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: sharing_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."sharing_members" (
    "member_id" "text" NOT NULL,
    "group_id" "text" NOT NULL,
    "token" "text" NOT NULL,
    "token_hash" "text",
    "display_name" "text",
    "role" "text" NOT NULL DEFAULT 'member',
    "joined_at" timestamp with time zone,
    "expires_at" timestamp with time zone,
    "revoked_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: sharing_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."sharing_items" (
    "item_id" "text" NOT NULL,
    "group_id" "text" NOT NULL,
    "item_type" "text" NOT NULL,
    "parent_item_id" "text",
    "payload" "jsonb" NOT NULL,
    "created_by" "text",
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "created_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: joined_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."joined_groups" (
    "group_id" "text" NOT NULL,
    "member_id" "text" NOT NULL,
    "token" "text",
    "token_ciphertext" "text",
    "token_iv" "text",
    "display_name" "text",
    "group_name" "text",
    "remote_backend_type" "text" NOT NULL,
    "remote_url" "text",
    "remote_anon_key" "text",
    "remote_anon_key_ciphertext" "text",
    "remote_anon_key_iv" "text",
    "owner_id" "uuid",
    "joined_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: verify_join_token; Type: FUNCTION; Schema: public; Owner: postgres
-- 1.301: uses token_hash + expiry + revocation
--

CREATE OR REPLACE FUNCTION "public"."verify_join_token"("p_token" "text")
RETURNS TABLE("group_id" "text", "group_name" "text", "member_id" "text",
              "display_name" "text", "backend_type" "text", "creator_name" "text")
LANGUAGE "sql" SECURITY DEFINER AS $$
  SELECT sg.id, sg.name, sm.member_id, sm.display_name, sg.backend_type,
         (SELECT cm.display_name FROM sharing_members cm
          WHERE cm.group_id = sg.id AND cm.role = 'creator' LIMIT 1)
  FROM sharing_members sm
  JOIN sharing_groups sg ON sg.id = sm.group_id
  WHERE sm.token_hash = encode(digest(p_token, 'sha256'), 'hex')
    AND sm.revoked_at IS NULL
    AND (sm.expires_at IS NULL OR sm.expires_at > now())
    AND sm.joined_at IS NULL;
$$;


--
-- Name: confirm_join; Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."confirm_join"("p_token" "text", "p_display_name" "text")
RETURNS "void"
LANGUAGE "sql" SECURITY DEFINER AS $$
  UPDATE sharing_members
  SET joined_at = now(),
      display_name = COALESCE(NULLIF(p_display_name, ''), display_name)
  WHERE token_hash = encode(digest(p_token, 'sha256'), 'hex')
    AND joined_at IS NULL
    AND revoked_at IS NULL
    AND (expires_at IS NULL OR expires_at > now());
$$;


--
-- Name: get_shared_items; Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."get_shared_items"("p_token" "text", "p_group_id" "text",
                                                        "p_item_type" "text" DEFAULT NULL)
RETURNS SETOF "public"."sharing_items"
LANGUAGE "sql" SECURITY DEFINER AS $$
  SELECT si.* FROM sharing_items si
  WHERE si.group_id = p_group_id
  AND (p_item_type IS NULL OR si.item_type = p_item_type)
  AND EXISTS (
    SELECT 1 FROM sharing_members sm
    WHERE sm.group_id = p_group_id
    AND sm.token_hash = encode(digest(p_token, 'sha256'), 'hex')
    AND sm.joined_at IS NOT NULL
    AND sm.revoked_at IS NULL
  );
$$;


--
-- Name: add_shared_item; Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."add_shared_item"(
  "p_token" "text", "p_item_id" "text", "p_group_id" "text", "p_item_type" "text",
  "p_payload" "jsonb", "p_member_id" "text", "p_parent_item_id" "text" DEFAULT NULL
)
RETURNS SETOF "public"."sharing_items"
LANGUAGE "sql" SECURITY DEFINER AS $$
  INSERT INTO sharing_items
    (item_id, group_id, item_type, parent_item_id, payload, created_by)
  SELECT p_item_id, p_group_id, p_item_type,
         p_parent_item_id, p_payload, p_member_id
  WHERE EXISTS (
    SELECT 1 FROM sharing_members sm
    WHERE sm.group_id = p_group_id
    AND sm.token_hash = encode(digest(p_token, 'sha256'), 'hex')
    AND sm.member_id = p_member_id
    AND sm.joined_at IS NOT NULL
    AND sm.revoked_at IS NULL
  )
  RETURNING *;
$$;


--
-- Name: update_shared_item; Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."update_shared_item"("p_token" "text", "p_item_id" "text",
                                                          "p_payload" "jsonb")
RETURNS SETOF "public"."sharing_items"
LANGUAGE "sql" SECURITY DEFINER AS $$
  UPDATE sharing_items si
  SET payload = p_payload, updated_at = now()
  WHERE si.item_id = p_item_id
  AND EXISTS (
    SELECT 1 FROM sharing_members sm
    WHERE sm.group_id = si.group_id
    AND sm.token_hash = encode(digest(p_token, 'sha256'), 'hex')
    AND sm.joined_at IS NOT NULL
    AND sm.revoked_at IS NULL
  )
  RETURNING *;
$$;


--
-- Name: delete_shared_item; Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."delete_shared_item"("p_token" "text", "p_item_id" "text")
RETURNS "void"
LANGUAGE "plpgsql" SECURITY DEFINER AS $$
BEGIN
  DELETE FROM sharing_items si
  WHERE si.item_id = p_item_id
  AND EXISTS (
    SELECT 1 FROM sharing_members sm
    WHERE sm.group_id = si.group_id
    AND sm.token_hash = encode(digest(p_token, 'sha256'), 'hex')
    AND sm.joined_at IS NOT NULL
    AND sm.revoked_at IS NULL
  );
END;
$$;


--
-- Name: get_group_members; Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."get_group_members"("p_token" "text", "p_group_id" "text")
RETURNS TABLE("member_id" "text", "display_name" "text", "role" "text",
              "joined_at" timestamp with time zone)
LANGUAGE "sql" SECURITY DEFINER AS $$
  SELECT sm.member_id, sm.display_name, sm.role, sm.joined_at
  FROM sharing_members sm
  WHERE sm.group_id = p_group_id
  AND EXISTS (
    SELECT 1 FROM sharing_members sm2
    WHERE sm2.group_id = p_group_id
    AND sm2.token_hash = encode(digest(p_token, 'sha256'), 'hex')
    AND sm2.joined_at IS NOT NULL
    AND sm2.revoked_at IS NULL
  );
$$;


--
-- Name: leave_group; Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."leave_group"("p_token" "text")
RETURNS "void"
LANGUAGE "plpgsql" SECURITY DEFINER AS $$
BEGIN
  DELETE FROM sharing_members
  WHERE token_hash = encode(digest(p_token, 'sha256'), 'hex')
  AND role != 'creator'
  AND joined_at IS NOT NULL
  AND revoked_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."revoke_member"("p_group_id" "text", "p_member_id" "text")
RETURNS "void"
LANGUAGE "sql" SECURITY DEFINER AS $$
  UPDATE sharing_members
  SET revoked_at = now()
  WHERE group_id = p_group_id
    AND member_id = p_member_id
    AND role != 'creator';
$$;


--
-- Name: birthdays birthdays_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."birthdays"
    ADD CONSTRAINT "birthdays_pkey" PRIMARY KEY ("id");


--
-- Name: habit_completions chore_completions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."habit_completions"
    ADD CONSTRAINT "chore_completions_pkey" PRIMARY KEY ("id");


--
-- Name: habits chores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."habits"
    ADD CONSTRAINT "chores_pkey" PRIMARY KEY ("id");


--
-- Name: daily_visits daily_visits_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."daily_visits"
    ADD CONSTRAINT "daily_visits_pkey" PRIMARY KEY ("visit_date", "owner_id");


--
-- Name: flashcard_notes flashcard_notes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."flashcard_notes"
    ADD CONSTRAINT "flashcard_notes_pkey" PRIMARY KEY ("id");


--
-- Name: flashcards flashcards_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."flashcards"
    ADD CONSTRAINT "flashcards_pkey" PRIMARY KEY ("id");


--
-- Name: list_items list_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."list_items"
    ADD CONSTRAINT "list_items_pkey" PRIMARY KEY ("id");


--
-- Name: lists lists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."lists"
    ADD CONSTRAINT "lists_pkey" PRIMARY KEY ("id");


--
-- Name: nvidia_usage nvidia_usage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."nvidia_usage"
    ADD CONSTRAINT "nvidia_usage_pkey" PRIMARY KEY ("id");


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."projects"
    ADD CONSTRAINT "projects_pkey" PRIMARY KEY ("id");


--
-- Name: prompts prompts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."prompts"
    ADD CONSTRAINT "prompts_pkey" PRIMARY KEY ("key");


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."settings"
    ADD CONSTRAINT "settings_pkey" PRIMARY KEY ("key");


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_pkey" PRIMARY KEY ("id");


--
-- Name: text_line_progress text_line_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."text_line_progress"
    ADD CONSTRAINT "text_line_progress_pkey" PRIMARY KEY ("id");


--
-- Name: texts texts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."texts"
    ADD CONSTRAINT "texts_pkey" PRIMARY KEY ("id");


--
-- Name: todos todos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."todos"
    ADD CONSTRAINT "todos_pkey" PRIMARY KEY ("id");


--
-- Name: vestiaire vestiaire_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."vestiaire"
    ADD CONSTRAINT "vestiaire_pkey" PRIMARY KEY ("id");


--
-- Name: sharing_groups sharing_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."sharing_groups"
    ADD CONSTRAINT "sharing_groups_pkey" PRIMARY KEY ("id");


--
-- Name: sharing_members sharing_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."sharing_members"
    ADD CONSTRAINT "sharing_members_pkey" PRIMARY KEY ("member_id");


--
-- Name: sharing_members sharing_members_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."sharing_members"
    ADD CONSTRAINT "sharing_members_token_key" UNIQUE ("token");


--
-- Name: sharing_items sharing_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."sharing_items"
    ADD CONSTRAINT "sharing_items_pkey" PRIMARY KEY ("item_id");


--
-- Name: joined_groups joined_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."joined_groups"
    ADD CONSTRAINT "joined_groups_pkey" PRIMARY KEY ("group_id");


--
-- Name: prompts prompts_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER "prompts_updated_at" BEFORE UPDATE ON "public"."prompts" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();


--
-- Name: todos set_todos_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER "set_todos_updated_at" BEFORE UPDATE ON "public"."todos" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();


--
-- Name: habits set_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER "set_updated_at" BEFORE UPDATE ON "public"."habits" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();


--
-- Name: tasks tasks_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER "tasks_updated_at" BEFORE UPDATE ON "public"."tasks" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();


--
-- Name: habit_completions chore_completions_chore_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."habit_completions"
    ADD CONSTRAINT "chore_completions_chore_id_fkey" FOREIGN KEY ("habit_id") REFERENCES "public"."habits"("id") ON DELETE CASCADE;


--
-- Name: list_items list_items_list_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."list_items"
    ADD CONSTRAINT "list_items_list_id_fkey" FOREIGN KEY ("list_id") REFERENCES "public"."lists"("id") ON DELETE CASCADE;


--
-- Name: text_line_progress text_line_progress_text_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."text_line_progress"
    ADD CONSTRAINT "text_line_progress_text_id_fkey" FOREIGN KEY ("text_id") REFERENCES "public"."texts"("id") ON DELETE CASCADE;


--
-- Name: sharing_members sharing_members_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."sharing_members"
    ADD CONSTRAINT "sharing_members_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."sharing_groups"("id") ON DELETE CASCADE;


--
-- Name: sharing_items sharing_items_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."sharing_items"
    ADD CONSTRAINT "sharing_items_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."sharing_groups"("id") ON DELETE CASCADE;


--
-- Name: sharing_items sharing_items_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."sharing_items"
    ADD CONSTRAINT "sharing_items_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."sharing_members"("member_id");


--
-- ===== ROW LEVEL SECURITY: ENABLE =====
--

ALTER TABLE "public"."birthdays" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."daily_visits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."flashcard_notes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."flashcards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."habit_completions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."habits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."list_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."lists" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."nvidia_usage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."projects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."prompts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tasks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."text_line_progress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."texts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."todos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."vestiaire" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."sharing_groups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."sharing_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."sharing_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."joined_groups" ENABLE ROW LEVEL SECURITY;


--
-- ===== ROW LEVEL SECURITY: POLICIES =====
--
-- Personal tables use "owner only": owner_id = auth.uid().
-- Supabase backend now requires mandatory auth — anon sees 0 rows.
-- Use claim_ownership() SECURITY DEFINER to claim legacy NULL rows.
-- Auto-set owner_id via trg_set_owner_id BEFORE INSERT trigger.
--

-- ── Helper functions ──
CREATE OR REPLACE FUNCTION set_owner_id()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.owner_id IS NULL THEN
    NEW.owner_id := auth.uid();
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION claim_ownership()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE uid UUID := auth.uid();
BEGIN
  IF uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  UPDATE projects SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE tasks SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE todos SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE habits SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE habit_completions SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE flashcards SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE flashcard_notes SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE texts SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE text_line_progress SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE birthdays SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE vestiaire SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE lists SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE list_items SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE settings SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE prompts SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE nvidia_usage SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE daily_visits SET owner_id = uid WHERE owner_id IS NULL;
  UPDATE joined_groups SET owner_id = uid WHERE owner_id IS NULL;
END;
$$;

-- ── Personal tables (owner only) ──────────────────────

CREATE POLICY "owner only" ON "public"."birthdays" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."birthdays" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."flashcard_notes" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."flashcard_notes" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."habit_completions" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."habit_completions" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."habits" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."habits" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."list_items" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."list_items" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."lists" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."lists" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."projects" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."projects" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."prompts" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."prompts" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."settings" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."settings" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."tasks" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."tasks" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."todos" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."todos" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."vestiaire" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."vestiaire" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

-- ── Previously open tables — now owner-only (1.398 fix) ─────────

CREATE POLICY "owner only" ON "public"."daily_visits" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."daily_visits" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."flashcards" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."flashcards" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."nvidia_usage" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."nvidia_usage" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."text_line_progress" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."text_line_progress" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

CREATE POLICY "owner only" ON "public"."texts" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."texts" FOR EACH ROW EXECUTE FUNCTION set_owner_id();

-- ── Sharing tables ────────────────────────────────────────────

CREATE POLICY "owner" ON "public"."sharing_groups" FOR ALL USING ("auth_owner_id" = "auth"."uid"());

CREATE POLICY "owner" ON "public"."sharing_members" FOR ALL USING ("group_id" IN (SELECT "id" FROM "public"."sharing_groups" WHERE "auth_owner_id" = "auth"."uid"()));

CREATE POLICY "owner" ON "public"."sharing_items" FOR ALL USING ("group_id" IN (SELECT "id" FROM "public"."sharing_groups" WHERE "auth_owner_id" = "auth"."uid"()));

CREATE POLICY "owner only" ON "public"."joined_groups" FOR ALL USING ("owner_id" = "auth"."uid"()) WITH CHECK ("owner_id" = "auth"."uid"());
CREATE TRIGGER trg_set_owner_id BEFORE INSERT ON "public"."joined_groups" FOR EACH ROW EXECUTE FUNCTION set_owner_id();


-- ===== SEED DATA =====

-- ===== INDEXES (perf — avoid seq scans on RLS owner_id lookups + shared pointers) =====
CREATE INDEX IF NOT EXISTS idx_projects_owner_id ON "public"."projects" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_tasks_owner_id ON "public"."tasks" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_todos_owner_id ON "public"."todos" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_habits_owner_id ON "public"."habits" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_habit_completions_owner_id ON "public"."habit_completions" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_flashcards_owner_id ON "public"."flashcards" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_flashcard_notes_owner_id ON "public"."flashcard_notes" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_texts_owner_id ON "public"."texts" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_text_line_progress_owner_id ON "public"."text_line_progress" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_birthdays_owner_id ON "public"."birthdays" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_vestiaire_owner_id ON "public"."vestiaire" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_lists_owner_id ON "public"."lists" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_list_items_owner_id ON "public"."list_items" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_prompts_owner_id ON "public"."prompts" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_settings_owner_id ON "public"."settings" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_nvidia_usage_owner_id ON "public"."nvidia_usage" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_daily_visits_owner_id ON "public"."daily_visits" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_joined_groups_owner_id ON "public"."joined_groups" ("owner_id");
CREATE INDEX IF NOT EXISTS idx_todos_shared_id ON "public"."todos" ("shared_id");
CREATE INDEX IF NOT EXISTS idx_todos_shared_group_id ON "public"."todos" ("shared_group_id");
CREATE INDEX IF NOT EXISTS idx_habits_shared_id ON "public"."habits" ("shared_id");
CREATE INDEX IF NOT EXISTS idx_habits_shared_group_id ON "public"."habits" ("shared_group_id");
CREATE INDEX IF NOT EXISTS idx_list_items_shared_id ON "public"."list_items" ("shared_id");
CREATE INDEX IF NOT EXISTS idx_list_items_shared_group_id ON "public"."list_items" ("shared_group_id");
CREATE INDEX IF NOT EXISTS idx_sharing_groups_auth_owner_id ON "public"."sharing_groups" ("auth_owner_id");
CREATE INDEX IF NOT EXISTS idx_sharing_members_group_id ON "public"."sharing_members" ("group_id");
CREATE INDEX IF NOT EXISTS idx_sharing_members_token_hash ON "public"."sharing_members" ("token_hash");
CREATE INDEX IF NOT EXISTS idx_sharing_items_group_id ON "public"."sharing_items" ("group_id");

INSERT INTO "public"."settings" ("key", "value") VALUES ('schema_version', '1.398')
ON CONFLICT ("key") DO UPDATE SET "value" = '1.398', "updated_at" = now();

INSERT INTO "public"."settings" ("key", "value") VALUES ('db_created_at', to_jsonb(now()::text))
ON CONFLICT ("key") DO NOTHING;

-- ===== REALTIME =====
-- Enable Supabase Realtime for cross-device live sync
ALTER PUBLICATION supabase_realtime ADD TABLE
  tasks, projects, todos, habits, habit_completions,
  birthdays, vestiaire, flashcards, flashcard_notes,
  prompts, settings, lists, list_items, daily_visits,
  sharing_groups, sharing_members, sharing_items;
