-- DeLaClaw — Supabase (PostgreSQL) full schema
-- Generated by pg_dump, cleaned of Supabase platform objects.
-- Run this in the Supabase SQL Editor to set up all tables.

--
-- Name: rls_auto_enable(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


--
-- Name: update_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION "public"."update_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = "heap";

--
-- Name: birthdays; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."birthdays" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "birthday" "date" NOT NULL,
    "note" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "avatar_url" "text"
);


--
-- Name: daily_visits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."daily_visits" (
    "visit_date" "date" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: flashcard_notes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."flashcard_notes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "content" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "proposed_front" "text",
    "proposed_back" "text",
    "proposal_status" "text",
    "proposed_deck" "text"
);


--
-- Name: flashcards; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."flashcards" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "deck" "text" DEFAULT 'Général'::"text" NOT NULL,
    "front" "text" NOT NULL,
    "back" "text" NOT NULL,
    "is_draft" boolean DEFAULT false,
    "stability" real DEFAULT 0,
    "difficulty" real DEFAULT 5,
    "last_review" timestamp with time zone,
    "next_review" timestamp with time zone,
    "review_count" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: habit_completions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."habit_completions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "habit_id" "uuid",
    "completed_at" timestamp with time zone DEFAULT "now"(),
    "note" "text"
);


--
-- Name: habits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."habits" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "frequency_rule" "text" NOT NULL,
    "category" "text" DEFAULT 'General'::"text",
    "next_due" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "is_draft" boolean DEFAULT false
);


--
-- Name: list_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."list_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "list_id" "uuid",
    "text" "text" NOT NULL,
    "checked" integer DEFAULT 0,
    "note" "text",
    "sort_order" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: lists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."lists" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "color" "text",
    "icon" "text",
    "sort_order" integer DEFAULT 0,
    "archived" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: nvidia_usage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."nvidia_usage" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "model" "text" NOT NULL,
    "prompt_tokens" integer DEFAULT 0,
    "completion_tokens" integer DEFAULT 0,
    "total_tokens" integer DEFAULT 0,
    "status" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."projects" (
    "id" "text" NOT NULL,
    "name" "text" NOT NULL,
    "color" "text" DEFAULT '#646cff'::"text" NOT NULL,
    "tech" "text",
    "links" "jsonb" DEFAULT '[]'::"jsonb",
    "sort_order" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "shortname" "text"
);


--
-- Name: prompts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."prompts" (
    "key" "text" NOT NULL,
    "text" "text" DEFAULT ''::"text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."settings" (
    "key" "text" NOT NULL,
    "value" "text",
    "updated_at" timestamp with time zone DEFAULT "now"()
);


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."tasks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "project" "text" NOT NULL,
    "text" "text" NOT NULL,
    "status" "text" DEFAULT 'todo'::"text" NOT NULL,
    "plan_note" "text",
    "hatch_response" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "sort_order" integer DEFAULT 0,
    CONSTRAINT "plan_max" CHECK (("char_length"("plan_note") <= 5000)),
    CONSTRAINT "response_max" CHECK (("char_length"("hatch_response") <= 5000)),
    CONSTRAINT "tasks_status_check" CHECK (("status" = ANY (ARRAY['todo'::"text", 'in-progress'::"text", 'review'::"text", 'approved'::"text", 'revision'::"text", 'draft'::"text", 'idea'::"text", 'idea-shipped'::"text", 'idea-plan-requested'::"text"]))),
    CONSTRAINT "text_max" CHECK (("char_length"("text") <= 5000))
);


--
-- Name: text_line_progress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."text_line_progress" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "text_id" "uuid" NOT NULL,
    "chunk_index" integer NOT NULL,
    "stability" double precision DEFAULT 0 NOT NULL,
    "difficulty" double precision DEFAULT 5 NOT NULL,
    "last_review" timestamp with time zone,
    "next_review" timestamp with time zone,
    "review_count" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


--
-- Name: texts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."texts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "deck" "text" NOT NULL,
    "title" "text" NOT NULL,
    "author" "text",
    "content" "text" NOT NULL,
    "lines_per_chunk" integer DEFAULT 4 NOT NULL,
    "context_lines" integer DEFAULT 3 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


--
-- Name: todos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."todos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "text" "text" NOT NULL,
    "done" boolean DEFAULT false,
    "priority" "text" DEFAULT 'normal'::"text",
    "due_date" timestamp with time zone,
    "snooze_until" timestamp with time zone,
    "category" "text" DEFAULT ''::"text",
    "sort_order" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "todos_priority_check" CHECK (("priority" = ANY (ARRAY['urgent'::"text", 'high'::"text", 'medium'::"text", 'low'::"text", 'normal'::"text"])))
);


--
-- Name: vestiaire; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."vestiaire" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "category" "text" DEFAULT 'Hauts'::"text" NOT NULL,
    "brand" "text",
    "size" "text",
    "color" "text",
    "note" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "purchase_status" "text",
    "sort_order" integer DEFAULT 0
);


--
-- Name: birthdays birthdays_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."birthdays"
    ADD CONSTRAINT "birthdays_pkey" PRIMARY KEY ("id");


--
-- Name: habit_completions chore_completions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."habit_completions"
    ADD CONSTRAINT "chore_completions_pkey" PRIMARY KEY ("id");


--
-- Name: habits chores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."habits"
    ADD CONSTRAINT "chores_pkey" PRIMARY KEY ("id");


--
-- Name: daily_visits daily_visits_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."daily_visits"
    ADD CONSTRAINT "daily_visits_pkey" PRIMARY KEY ("visit_date");


--
-- Name: flashcard_notes flashcard_notes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."flashcard_notes"
    ADD CONSTRAINT "flashcard_notes_pkey" PRIMARY KEY ("id");


--
-- Name: flashcards flashcards_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."flashcards"
    ADD CONSTRAINT "flashcards_pkey" PRIMARY KEY ("id");


--
-- Name: list_items list_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."list_items"
    ADD CONSTRAINT "list_items_pkey" PRIMARY KEY ("id");


--
-- Name: lists lists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."lists"
    ADD CONSTRAINT "lists_pkey" PRIMARY KEY ("id");


--
-- Name: nvidia_usage nvidia_usage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."nvidia_usage"
    ADD CONSTRAINT "nvidia_usage_pkey" PRIMARY KEY ("id");


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."projects"
    ADD CONSTRAINT "projects_pkey" PRIMARY KEY ("id");


--
-- Name: prompts prompts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."prompts"
    ADD CONSTRAINT "prompts_pkey" PRIMARY KEY ("key");


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."settings"
    ADD CONSTRAINT "settings_pkey" PRIMARY KEY ("key");


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_pkey" PRIMARY KEY ("id");


--
-- Name: text_line_progress text_line_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."text_line_progress"
    ADD CONSTRAINT "text_line_progress_pkey" PRIMARY KEY ("id");


--
-- Name: texts texts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."texts"
    ADD CONSTRAINT "texts_pkey" PRIMARY KEY ("id");


--
-- Name: todos todos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."todos"
    ADD CONSTRAINT "todos_pkey" PRIMARY KEY ("id");


--
-- Name: vestiaire vestiaire_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."vestiaire"
    ADD CONSTRAINT "vestiaire_pkey" PRIMARY KEY ("id");


--
-- Name: prompts prompts_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER "prompts_updated_at" BEFORE UPDATE ON "public"."prompts" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();


--
-- Name: todos set_todos_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER "set_todos_updated_at" BEFORE UPDATE ON "public"."todos" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();


--
-- Name: habits set_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER "set_updated_at" BEFORE UPDATE ON "public"."habits" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();


--
-- Name: tasks tasks_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER "tasks_updated_at" BEFORE UPDATE ON "public"."tasks" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();


--
-- Name: habit_completions chore_completions_chore_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."habit_completions"
    ADD CONSTRAINT "chore_completions_chore_id_fkey" FOREIGN KEY ("habit_id") REFERENCES "public"."habits"("id") ON DELETE CASCADE;


--
-- Name: list_items list_items_list_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."list_items"
    ADD CONSTRAINT "list_items_list_id_fkey" FOREIGN KEY ("list_id") REFERENCES "public"."lists"("id") ON DELETE CASCADE;


--
-- Name: text_line_progress text_line_progress_text_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."text_line_progress"
    ADD CONSTRAINT "text_line_progress_text_id_fkey" FOREIGN KEY ("text_id") REFERENCES "public"."texts"("id") ON DELETE CASCADE;


--
-- Name: habit_completions Allow all; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all" ON "public"."habit_completions" USING (true) WITH CHECK (true);


--
-- Name: habits Allow all; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all" ON "public"."habits" USING (true) WITH CHECK (true);


--
-- Name: daily_visits Allow all access to daily_visits; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all access to daily_visits" ON "public"."daily_visits" USING (true) WITH CHECK (true);


--
-- Name: projects Allow all delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all delete" ON "public"."projects" FOR DELETE USING (true);


--
-- Name: prompts Allow all delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all delete" ON "public"."prompts" FOR DELETE USING (true);


--
-- Name: tasks Allow all delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all delete" ON "public"."tasks" FOR DELETE USING (true);


--
-- Name: birthdays Allow all for anon; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all for anon" ON "public"."birthdays" TO "anon" USING (true) WITH CHECK (true);


--
-- Name: flashcard_notes Allow all for anon; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all for anon" ON "public"."flashcard_notes" TO "anon" USING (true) WITH CHECK (true);


--
-- Name: flashcards Allow all for anon; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all for anon" ON "public"."flashcards" TO "anon" USING (true) WITH CHECK (true);


--
-- Name: vestiaire Allow all for anon; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all for anon" ON "public"."vestiaire" TO "anon" USING (true) WITH CHECK (true);


--
-- Name: projects Allow all insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all insert" ON "public"."projects" FOR INSERT WITH CHECK (true);


--
-- Name: prompts Allow all insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all insert" ON "public"."prompts" FOR INSERT WITH CHECK (true);


--
-- Name: tasks Allow all insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all insert" ON "public"."tasks" FOR INSERT WITH CHECK (true);


--
-- Name: projects Allow all read; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all read" ON "public"."projects" FOR SELECT USING (true);


--
-- Name: prompts Allow all read; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all read" ON "public"."prompts" FOR SELECT USING (true);


--
-- Name: tasks Allow all read; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all read" ON "public"."tasks" FOR SELECT USING (true);


--
-- Name: projects Allow all update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all update" ON "public"."projects" FOR UPDATE USING (true);


--
-- Name: prompts Allow all update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all update" ON "public"."prompts" FOR UPDATE USING (true);


--
-- Name: tasks Allow all update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow all update" ON "public"."tasks" FOR UPDATE USING (true);


--
-- Name: birthdays allow_all_birthdays; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "allow_all_birthdays" ON "public"."birthdays" USING (true) WITH CHECK (true);


--
-- Name: habit_completions allow_all_chore_completions; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "allow_all_chore_completions" ON "public"."habit_completions" USING (true) WITH CHECK (true);


--
-- Name: habits allow_all_chores; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "allow_all_chores" ON "public"."habits" USING (true) WITH CHECK (true);


--
-- Name: flashcard_notes allow_all_flashcard_notes; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "allow_all_flashcard_notes" ON "public"."flashcard_notes" USING (true) WITH CHECK (true);


--
-- Name: flashcards allow_all_flashcards; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "allow_all_flashcards" ON "public"."flashcards" USING (true) WITH CHECK (true);


--
-- Name: nvidia_usage allow_all_nvidia_usage; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "allow_all_nvidia_usage" ON "public"."nvidia_usage" USING (true) WITH CHECK (true);


--
-- Name: projects allow_all_projects; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "allow_all_projects" ON "public"."projects" USING (true) WITH CHECK (true);


--
-- Name: prompts allow_all_prompts; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "allow_all_prompts" ON "public"."prompts" USING (true) WITH CHECK (true);


--
-- Name: settings allow_all_settings; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "allow_all_settings" ON "public"."settings" USING (true) WITH CHECK (true);


--
-- Name: tasks allow_all_tasks; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "allow_all_tasks" ON "public"."tasks" USING (true) WITH CHECK (true);


--
-- Name: text_line_progress allow_all_text_line_progress; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "allow_all_text_line_progress" ON "public"."text_line_progress" USING (true) WITH CHECK (true);


--
-- Name: texts allow_all_texts; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "allow_all_texts" ON "public"."texts" USING (true) WITH CHECK (true);


--
-- Name: todos allow_all_todos; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "allow_all_todos" ON "public"."todos" USING (true) WITH CHECK (true);


--
-- Name: vestiaire allow_all_vestiaire; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "allow_all_vestiaire" ON "public"."vestiaire" USING (true) WITH CHECK (true);


--
-- Name: birthdays; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."birthdays" ENABLE ROW LEVEL SECURITY;

--
-- Name: daily_visits; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."daily_visits" ENABLE ROW LEVEL SECURITY;

--
-- Name: flashcard_notes; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."flashcard_notes" ENABLE ROW LEVEL SECURITY;

--
-- Name: flashcards; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."flashcards" ENABLE ROW LEVEL SECURITY;

--
-- Name: habit_completions; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."habit_completions" ENABLE ROW LEVEL SECURITY;

--
-- Name: habits; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."habits" ENABLE ROW LEVEL SECURITY;

--
-- Name: list_items; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."list_items" ENABLE ROW LEVEL SECURITY;

--
-- Name: list_items list_items_policy; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "list_items_policy" ON "public"."list_items" USING (true) WITH CHECK (true);


--
-- Name: lists; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."lists" ENABLE ROW LEVEL SECURITY;

--
-- Name: lists lists_policy; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "lists_policy" ON "public"."lists" USING (true) WITH CHECK (true);


--
-- Name: nvidia_usage; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."nvidia_usage" ENABLE ROW LEVEL SECURITY;

--
-- Name: projects; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."projects" ENABLE ROW LEVEL SECURITY;

--
-- Name: prompts; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."prompts" ENABLE ROW LEVEL SECURITY;

--
-- Name: settings; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."settings" ENABLE ROW LEVEL SECURITY;

--
-- Name: tasks; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."tasks" ENABLE ROW LEVEL SECURITY;

--
-- Name: text_line_progress; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."text_line_progress" ENABLE ROW LEVEL SECURITY;

--
-- Name: texts; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."texts" ENABLE ROW LEVEL SECURITY;

--
-- Name: todos; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."todos" ENABLE ROW LEVEL SECURITY;

--
-- Name: todos todos_open_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "todos_open_delete" ON "public"."todos" FOR DELETE USING (true);


--
-- Name: todos todos_open_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "todos_open_insert" ON "public"."todos" FOR INSERT WITH CHECK (true);


--
-- Name: todos todos_open_read; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "todos_open_read" ON "public"."todos" FOR SELECT USING (true);


--
-- Name: todos todos_open_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "todos_open_update" ON "public"."todos" FOR UPDATE USING (true) WITH CHECK (true);


--
-- Name: vestiaire; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."vestiaire" ENABLE ROW LEVEL SECURITY;


-- ===== SEED DATA =====

INSERT INTO "public"."settings" ("key", "value") VALUES ('schema_version', '1.099')
ON CONFLICT ("key") DO UPDATE SET "value" = '1.099', "updated_at" = now();

INSERT INTO "public"."settings" ("key", "value") VALUES ('db_created_at', to_jsonb(now()::text))
ON CONFLICT ("key") DO NOTHING;

-- ===== REALTIME =====
-- Enable Supabase Realtime for cross-device live sync
ALTER PUBLICATION supabase_realtime ADD TABLE
  tasks, projects, todos, habits, habit_completions,
  birthdays, vestiaire, flashcards, flashcard_notes,
  prompts, settings, lists, list_items, daily_visits;
